apiVersion: v1 
kind: Secret 
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  DB_USER: {{ .Values.backend.secret.DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.backend.secret.DB_PASSWORD | b64enc }}
  MYSQL_USER: {{ .Values.mysql.secret.MYSQL_USER | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.secret.MYSQL_PASSWORD | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secret.MYSQL_ROOT_PASSWORD | b64enc }}
  MYSQL_DATABASE: {{ .Values.mysql.secret.MYSQL_DATABASE | b64enc }}
  

